apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-depl
spec:

  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
#      serviceAccountName: my-service-account
      containers:
        - name: email
          image: shedzo/email-paas
#          volumeMounts:
#            - name: k8s-token
#              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#              readOnly: true
          env:
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name


